# docker-compose.test.yml
version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    container_name: blog-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_system_test
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  blog-system-test:
    build: .
    container_name: blog-system-test
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - DB_USERNAME=blog_user
      - DB_PASSWORD=blog_password
      - DB_NAME=blog_system_test
      - JWT_SECRET=test_secret_key_for_testing_only
      - APP_ENV=testing
      - LOG_LEVEL=debug
    depends_on:
      mysql-test:
        condition: service_healthy
    volumes:
      - .:/app
    command: go run main.go
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/posts"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_test_data:
